#' VAT Status data with 13 variables
#'
#' @format A data frame with 20000 rows and 13 variables
#' 
#' \describe{
#'   \item{ID}{integer}
#'   \item{VATStatusAge}{double}
#'   \item{VATStartAge}{double}
#'   \item{VATEndAge}{double}
#'   \item{VATCollectionStartAge}{double}
#'   \item{VATCollectionEndAge}{double}
#'   \item{VATCollectionUpdateAge}{double}
#'   \item{VATCollectionPublishAge}{double}
#'   \item{VATInactivationAge}{double}
#'   \item{VATReactivationAge}{double}
#'   \item{VATCancellationAge}{logical}
#'   \item{VATSplitStartAge}{double}
#'   \item{VATSplitCancellationAge}{logical}
#' }
#'
#'
"VATStatus"

#' Tax Overdues data with 8 variables
#'
#' @format A data frame with 20004 rows and 8 variables
#' 
#' \describe{
#'   \item{Year}{integer}
#'   \item{MainOustandingTaxLiab}{double}
#'   \item{SecondaryTaxLiab}{double}
#'   \item{ContestedTaxLiab}{double}
#'   \item{TotalTaxLiab}{double}
#'   \item{UncontestedTaxLiab}{double}
#'   \item{BudgetType}{character}
#'   \item{ID}{double}
#' }
#'
#'
"TaxOverdues"

#' MovablesRegistry data with 13 variables
#'
#' @format A data frame with 5863 rows and 13 variables
#' 
#' \describe{
#'   \item{ID}{double}
#'   \item{NoCreditors}{double}
#'   \item{OldestRecord}{double}
#'   \item{NewestRecord}{double}
#'   \item{NoRecords}{double}
#'   \item{NoActiveCreditors}{double}
#'   \item{OldestActiveRecord}{double}
#'   \item{NewestActiveRecord}{double}
#'   \item{NoActiveRecords}{double}
#'   \item{AvgRecords}{double}
#'   \item{AvgRecordsAge}{double}
#'   \item{AvgActiveRecords}{double}
#'   \item{AvgActiveRecordsAge}{double}
#' }
#'
#'
"MovablesRegistry"

#' InsolvencyRegistry data with 5 variables
#'
#' @format A data frame with 32107 rows and 5 variables
#' 
#' \describe{
#'   \item{ID}{integer}
#'   \item{FirstRegistrationAge}{double}
#'   \item{LastRegistrationAge}{double}
#'   \item{TotalNoRecords}{double}
#'   \item{AverageNoRecords}{double}
#' }
#'
#'
"InsolvencyRegistry"

#' Financials 2018 data with 165 variables
#'
#' @format A data frame with 1240 rows and 165 variables
#' 
#' \describe{
#'   \item{ID}{integer}
#'   \item{TotalSales}{double}
#'   \item{TotalNetSales}{double}
#'   \item{TotalOtherIncome}{double}
#'   \item{OwnWorkCapitalised}{double}
#'   \item{ChangeInventoryProd}{double}
#'   \item{OtherOperatingIncome}{double}
#'   \item{iOOIProvisionRelease}{double}
#'   \item{iOOISubsidies}{double}
#'   \item{iOOISubsidiesExtraord}{double}
#'   \item{iOOIExtraordinary}{double}
#'   \item{TotalRevenues}{double}
#'   \item{Cogs}{double}
#'   \item{iCogsRawMaterials}{double}
#'   \item{iCogsMerchandise}{double}
#'   \item{iCogsSubdeliveries}{double}
#'   \item{PersonnelExpenses}{double}
#'   \item{SGAOtherOpExpenses}{double}
#'   \item{iSGABadDebtProv}{double}
#'   \item{iSGAExtraordinary}{double}
#'   \item{DepreciationAndAmortization}{double}
#'   \item{Ebit}{double}
#'   \item{Ebitda}{double}
#'   \item{EbitdaMargin}{character}
#'   \item{TradingMargin}{character}
#'   \item{ProductionMargin}{double}
#'   \item{InterestIncome}{double}
#'   \item{InterestExpense}{double}
#'   \item{NetInterestResult}{double}
#'   \item{FXGains}{double}
#'   \item{FXLosses}{double}
#'   \item{NetFXResult}{double}
#'   \item{GroupInvestResult}{double}
#'   \item{iSubsidiarySales}{double}
#'   \item{NetFinancialResult}{double}
#'   \item{ExtraordinaryIncome}{double}
#'   \item{iExtraordFixedAssetsReval}{double}
#'   \item{iExtraordProvRelease}{double}
#'   \item{ExtraordinaryExpenses}{double}
#'   \item{iExtraordFAWriteDowns}{double}
#'   \item{iExtraordProvTransfer}{double}
#'   \item{NetExtraordinaryResult}{double}
#'   \item{IncomeTaxes}{double}
#'   \item{NetProfitLoss}{double}
#'   \item{CashBankDeposits}{double}
#'   \item{STSecurities}{double}
#'   \item{OtherSTFinAssets}{double}
#'   \item{CashAndCashEquivalents}{double}
#'   \item{TradeReceivables}{double}
#'   \item{IntragroupReceivables}{double}
#'   \item{ReceivablesTaxAuthority}{double}
#'   \item{OtherReceivables}{double}
#'   \item{iOtherReceivablesOwners}{double}
#'   \item{TotalReceivables}{double}
#'   \item{RawMaterials}{double}
#'   \item{Merchandise}{double}
#'   \item{TotalInventory}{double}
#'   \item{PrepaidExpenses}{double}
#'   \item{TotalCurrentAssets}{double}
#'   \item{LandBuildings}{double}
#'   \item{PlantMachinery}{double}
#'   \item{FurnitureEquipment}{double}
#'   \item{AdvancesTangibleAssets}{double}
#'   \item{TangibleAssetsInProgress}{double}
#'   \item{TangibleFixedAssets}{double}
#'   \item{RightsPatents}{double}
#'   \item{OtherCapitalizedExpenses}{double}
#'   \item{IntangibleFixedAssets}{double}
#'   \item{OtherLTFinancialAssets}{double}
#'   \item{TotalFixedAssets}{double}
#'   \item{TotalAssets}{double}
#'   \item{STBankLoans}{double}
#'   \item{OtherSTLoansNonBank}{double}
#'   \item{SubtotalSTInterestBearingDebt}{double}
#'   \item{STAccountsPayables}{double}
#'   \item{STIntragroupPayables}{double}
#'   \item{STProvisions}{double}
#'   \item{AccruedExpenses}{double}
#'   \item{PayablesTaxAuthority}{double}
#'   \item{DividendsPayable}{double}
#'   \item{OtherSTLiabilities}{double}
#'   \item{TotalSTLiabilities}{double}
#'   \item{LTBankLoans}{double}
#'   \item{SHLoansGranted}{double}
#'   \item{CapitalizedLeaseObligations}{double}
#'   \item{SubtotalLTInterestBearingDebt}{double}
#'   \item{OtherLTLiabilities}{double}
#'   \item{TotalLTLiabilities}{double}
#'   \item{TotalLiabilities}{double}
#'   \item{SeniorDebt}{double}
#'   \item{ShareCapital}{double}
#'   \item{SharePremium}{double}
#'   \item{RevaluationReserve}{double}
#'   \item{OtherReserves}{double}
#'   \item{AccumulatedRetainedEarnings}{double}
#'   \item{TreasuryStock}{double}
#'   \item{OtherEquity}{double}
#'   \item{Equity}{double}
#'   \item{EquityRatio}{double}
#'   \item{BalFigCheck}{double}
#'   \item{NoEmployeesEop}{double}
#'   \item{NoEmployeesAvg}{double}
#'   \item{ProductivityPerEmployee}{double}
#'   \item{AvgEmployeeCost}{double}
#'   \item{CollectionPeriod}{double}
#'   \item{InventoryPeriod}{double}
#'   \item{PayablesPeriod}{double}
#'   \item{CurrentRatio}{double}
#'   \item{QuickRatio}{double}
#'   \item{LiquidAssetsRatio}{double}
#'   \item{OperatingCycle}{double}
#'   \item{FinancingGap}{double}
#'   \item{WorkingCapitalNeed}{double}
#'   \item{NetSeniorDebtByEbitda}{double}
#'   \item{InterestCover}{double}
#'   \item{EBITDAInterestCoverage}{character}
#'   \item{EstimatedInterestRate}{character}
#'   \item{AssetTurnover}{double}
#'   \item{FixedAssetTurnover}{double}
#'   \item{CurrentAssetTurnover}{double}
#'   \item{Gearing}{double}
#'   \item{Leverage}{double}
#'   \item{STFinancingRatio}{double}
#'   \item{WkLoansRatio}{double}
#'   \item{ReturnOnAssets}{double}
#'   \item{ReturnOnFixedAssets}{double}
#'   \item{ReturnOnCurrentAssets}{double}
#'   \item{ReturnOnEquity}{double}
#'   \item{CFSustTotalSales}{double}
#'   \item{CFSustEBITDA}{double}
#'   \item{CFMaintCapex}{double}
#'   \item{CFInterestExpense}{double}
#'   \item{CFIncomeTax}{double}
#'   \item{CFMandatoryDividends}{double}
#'   \item{CFFreeCashFlow}{double}
#'   \item{CFMultiplier}{double}
#'   \item{CFCashFlowValuation}{double}
#'   \item{CFMaxLeverageST}{double}
#'   \item{CFMaxLeverageLT}{double}
#'   \item{CFSeniorDebt}{double}
#'   \item{CFWkExcessDeficit}{double}
#'   \item{CFHeadroomAvailable}{double}
#'   \item{CFHeadroomST}{double}
#'   \item{CFHeadroomLT}{double}
#'   \item{CFSeniorDebtByFCF}{double}
#'   \item{CFHeadroomByFCF}{double}
#'   \item{EstimatedFreeAssets}{double}
#'   \item{TotalOverdueDebts}{double}
#'   \item{TotalOverduePayables}{double}
#'   \item{OverduePayables1M}{double}
#'   \item{OverduePayables3M}{double}
#'   \item{OverduePayables12M}{double}
#'   \item{OverdueTaxDebts}{double}
#'   \item{OverdueDebtsOther}{double}
#'   \item{iTotalOverdueReceivables}{double}
#'   \item{TotalOverdueReceivables}{double}
#'   \item{OverdueReceivablesBacklog}{double}
#'   \item{iOverdueReceivablesBudget}{double}
#'   \item{OverdueTaxReceivables}{double}
#'   \item{LTReceivables}{double}
#'   \item{UnsaleableInventory}{double}
#'   \item{ShareOverdueDebts}{double}
#'   \item{ShareOverduePayables}{double}
#'   \item{ShareOverdueReceivables}{double}
#'   \item{ShareUnsaleableInventory}{double}
#' }
#'
#'
"Financials2018"

#' CompanyData2018 data with 285 variables
#'
#' @format A data frame with 13012 rows and 285 variables
#' 
#' \describe{
#'   \item{LegalStatusCode}{double}
#'   \item{Judet}{character}
#'   \item{NaceFinal}{double}
#'   \item{Year}{double}
#'   \item{CompanyRegDate}{character}
#'   \item{CompanyAge}{double}
#'   \item{CompanyLastReg}{double}
#'   \item{NaceCode}{double}
#'   \item{NaceAnaf2017}{double}
#'   \item{NaceActualDiff}{double}
#'   \item{ApartmentCompany}{double}
#'   \item{OrganizationType}{character}
#'   \item{IndustrySector}{character}
#'   \item{IndustryRisk}{character}
#'   \item{Region}{character}
#'   \item{OperatingCode}{double}
#'   \item{InsolvencyFlag}{double}
#'   \item{CriminalPersecutionFlag}{double}
#'   \item{MergersFlag}{double}
#'   \item{AdverseInformationFlag}{double}
#'   \item{Art15Flag}{double}
#'   \item{LegalStatus}{character}
#'   \item{IsFingerPrinciple}{logical}
#'   \item{CodGroupFinal}{double}
#'   \item{ID}{integer}
#'   \item{YearsManagerialExperience}{double}
#'   \item{OneManShow}{double}
#'   \item{FamilyCompany}{double}
#'   \item{GenCountAdminPI}{double}
#'   \item{GenCountAdminLE}{double}
#'   \item{GenCountAdminList}{double}
#'   \item{GenCountOwners}{double}
#'   \item{GenSumOwnership}{double}
#'   \item{GenMinOwnership}{double}
#'   \item{GenMaxOwnership}{double}
#'   \item{GenAvgOwnership}{double}
#'   \item{GenMinOwnersStart}{double}
#'   \item{GenMaxOwnersStart}{double}
#'   \item{GenAvgOwnersStart}{double}
#'   \item{GenCountOwnersPI}{double}
#'   \item{GenCountOwnersLE}{double}
#'   \item{GenCountOwnersList}{double}
#'   \item{GenSumOwnershipPI}{double}
#'   \item{GenSumOwnershipLE}{double}
#'   \item{GenSumOwnershipList}{double}
#'   \item{GenMinOwnershipPI}{double}
#'   \item{GenMinOwnershipLE}{double}
#'   \item{GenMinOwnershipList}{double}
#'   \item{GenMaxOwnershipPI}{double}
#'   \item{GenMaxOwnershipLE}{double}
#'   \item{GenMaxOwnershipList}{double}
#'   \item{GenAvgOwnershipPI}{double}
#'   \item{GenAvgOwnershipLE}{double}
#'   \item{GenAvgOwnershipList}{double}
#'   \item{GenMinOwnersStartPI}{double}
#'   \item{GenMinOwnersStartLE}{double}
#'   \item{GenMinOwnersStartList}{double}
#'   \item{GenMaxOwnersStartPI}{double}
#'   \item{GenMaxOwnersStartLE}{double}
#'   \item{GenMaxOwnersStartList}{double}
#'   \item{GenAvgOwnersStartPI}{double}
#'   \item{GenAvgOwnersStartLE}{double}
#'   \item{GenAvgOwnersStartList}{double}
#'   \item{GenMinOwnersAgePI}{double}
#'   \item{GenMaxOwnersAgePI}{double}
#'   \item{GenAvgOwnersAgePI}{double}
#'   \item{GenCountOwnersRes}{double}
#'   \item{GenSumOwnershipRes}{double}
#'   \item{GenMinOwnershipRes}{double}
#'   \item{GenMaxOwnershipRes}{double}
#'   \item{GenAvgOwnershipRes}{double}
#'   \item{GenMinOwnersResStart}{double}
#'   \item{GenMaxOwnersResStart}{double}
#'   \item{GenAvgOwnersResStart}{double}
#'   \item{GenCountOwnersPIRes}{double}
#'   \item{GenCountOwnersLERes}{double}
#'   \item{GenSumOwnershipPIRes}{double}
#'   \item{GenSumOwnershipLERes}{double}
#'   \item{GenMinOwnershipPIRes}{double}
#'   \item{GenMinOwnershipLERes}{double}
#'   \item{GenMaxOwnershipPIRes}{double}
#'   \item{GenMaxOwnershipLERes}{double}
#'   \item{GenAvgOwnershipPIRes}{double}
#'   \item{GenAvgOwnershipLERes}{double}
#'   \item{GenMinOwnersStartPIRes}{double}
#'   \item{GenMinOwnersStartLERes}{double}
#'   \item{GenMaxOwnersStartPIRes}{double}
#'   \item{GenMaxOwnersStartLERes}{double}
#'   \item{GenAvgOwnersStartPIRes}{double}
#'   \item{GenAvgOwnersStartLERes}{double}
#'   \item{GenMinOwnersAgePIRes}{double}
#'   \item{GenMinOwnersAgeLERes}{logical}
#'   \item{GenMaxOwnersAgePIRes}{double}
#'   \item{GenMaxOwnersAgeLERes}{logical}
#'   \item{GenAvgOwnersAgePIRes}{double}
#'   \item{GenAvgOwnersAgeLERes}{logical}
#'   \item{GenCountOwnersNonRes}{double}
#'   \item{GenSumOwnershipNonRes}{double}
#'   \item{GenMinOwnershipNonRes}{double}
#'   \item{GenMaxOwnershipNonRes}{double}
#'   \item{GenAvgOwnershipNonRes}{double}
#'   \item{GenMinOwnersNonResStart}{double}
#'   \item{GenMaxOwnersNonResStart}{double}
#'   \item{GenAvgOwnersNonResStart}{double}
#'   \item{GenCountOwnersPINonRes}{double}
#'   \item{GenCountOwnersLENonRes}{double}
#'   \item{GenSumOwnershipPINonRes}{double}
#'   \item{GenSumOwnershipLENonRes}{double}
#'   \item{GenMinOwnershipPINonRes}{double}
#'   \item{GenMinOwnershipLENonRes}{double}
#'   \item{GenMaxOwnershipPINonRes}{double}
#'   \item{GenMaxOwnershipLENonRes}{double}
#'   \item{GenAvgOwnershipPINonRes}{double}
#'   \item{GenAvgOwnershipLENonRes}{double}
#'   \item{GenMinOwnersStartPINonRes}{double}
#'   \item{GenMinOwnersStartLENonRes}{double}
#'   \item{GenMaxOwnersStartPINonRes}{double}
#'   \item{GenMaxOwnersStartLENonRes}{double}
#'   \item{GenAvgOwnersStartPINonRes}{double}
#'   \item{GenAvgOwnersStartLENonRes}{double}
#'   \item{GenMinOwnersAgePINonRes}{double}
#'   \item{GenMinOwnersAgeLENonRes}{logical}
#'   \item{GenMaxOwnersAgePINonRes}{double}
#'   \item{GenMaxOwnersAgeLENonRes}{logical}
#'   \item{GenAvgOwnersAgePINonRes}{double}
#'   \item{GenAvgOwnersAgeLENonRes}{logical}
#'   \item{GenCountAdmin}{double}
#'   \item{GenMinAdminStart}{double}
#'   \item{GenMaxAdminStart}{double}
#'   \item{GenAvgAdminStart}{double}
#'   \item{GenMinAdminStartPI}{double}
#'   \item{GenMinAdminStartLE}{logical}
#'   \item{GenMinAdminStartList}{logical}
#'   \item{GenMaxAdminStartPI}{double}
#'   \item{GenMaxAdminStartLE}{logical}
#'   \item{GenMaxAdminStartList}{logical}
#'   \item{GenAvgAdminStartPI}{double}
#'   \item{GenAvgAdminStartLE}{logical}
#'   \item{GenAvgAdminStartList}{logical}
#'   \item{GenMinAdminAgePI}{double}
#'   \item{GenMaxAdminAgePI}{double}
#'   \item{GenAvgAdminAgePI}{double}
#'   \item{GenCountAdminRes}{double}
#'   \item{GenMinAdminResStart}{double}
#'   \item{GenMaxAdminResStart}{double}
#'   \item{GenAvgAdminResStart}{double}
#'   \item{GenCountAdminPIRes}{double}
#'   \item{GenCountAdminLERes}{double}
#'   \item{GenMinAdminStartPIRes}{double}
#'   \item{GenMinAdminStartLERes}{logical}
#'   \item{GenMaxAdminStartPIRes}{double}
#'   \item{GenMaxAdminStartLERes}{logical}
#'   \item{GenAvgAdminStartPIRes}{double}
#'   \item{GenAvgAdminStartLERes}{logical}
#'   \item{GenMinAdminAgePIRes}{double}
#'   \item{GenMaxAdminAgePIRes}{double}
#'   \item{GenAvgAdminAgePIRes}{double}
#'   \item{GenCountAdminNonRes}{double}
#'   \item{GenMinAdminNonResStart}{double}
#'   \item{GenMaxAdminNonResStart}{double}
#'   \item{GenAvgAdminNonResStart}{double}
#'   \item{GenCountAdminPINonRes}{double}
#'   \item{GenCountAdminLENonRes}{double}
#'   \item{GenMinAdminStartPINonRes}{double}
#'   \item{GenMinAdminStartLENonRes}{logical}
#'   \item{GenMaxAdminStartPINonRes}{double}
#'   \item{GenMaxAdminStartLENonRes}{logical}
#'   \item{GenAvgAdminStartPINonRes}{double}
#'   \item{GenAvgAdminStartLENonRes}{logical}
#'   \item{GenMinAdminAgePINonRes}{double}
#'   \item{GenMaxAdminAgePINonRes}{double}
#'   \item{GenAvgAdminAgePINonRes}{double}
#'   \item{GenCountAuditor}{logical}
#'   \item{GenMinAuditorStart}{logical}
#'   \item{GenMaxAuditorStart}{logical}
#'   \item{GenAvgAuditorStart}{logical}
#'   \item{GenMinAuditorStartPI}{logical}
#'   \item{GenMinAuditorStartLE}{logical}
#'   \item{GenMinAuditorStartList}{logical}
#'   \item{GenMaxAuditorStartPI}{logical}
#'   \item{GenMaxAuditorStartLE}{logical}
#'   \item{GenMaxAuditorStartList}{logical}
#'   \item{GenAvgAuditorStartPI}{logical}
#'   \item{GenAvgAuditorStartLE}{logical}
#'   \item{GenAvgAuditorStartList}{logical}
#'   \item{GenCountFormerOwners}{logical}
#'   \item{GenSumFormerOwnership}{logical}
#'   \item{GenMinFormerOwnership}{logical}
#'   \item{GenMaxFormerOwnership}{logical}
#'   \item{GenAvgFormerOwnership}{logical}
#'   \item{GenMinFormerOwnersEnd}{logical}
#'   \item{GenMaxOwnersEnd}{logical}
#'   \item{GenAvgOwnersEnd}{logical}
#'   \item{GenCountFormerOwnersPI}{logical}
#'   \item{GenCountFormerOwnersLE}{logical}
#'   \item{GenCountFormerOwnersList}{logical}
#'   \item{GenSumFormerOwnershipPI}{logical}
#'   \item{GenSumFormerOwnershipLE}{logical}
#'   \item{GenSumFormerOwnershipList}{logical}
#'   \item{GenMinFormerOwnershipPI}{logical}
#'   \item{GenMinFormerOwnershipLE}{logical}
#'   \item{GenMinFormerOwnershipList}{logical}
#'   \item{GenMaxFormerOwnershipPI}{logical}
#'   \item{GenMaxFormerOwnershipLE}{logical}
#'   \item{GenMaxFormerOwnershipList}{logical}
#'   \item{GenAvgFormerOwnershipPI}{logical}
#'   \item{GenAvgFormerOwnershipLE}{logical}
#'   \item{GenAvgFormerOwnershipList}{logical}
#'   \item{GenMinFormerOwnersEndPI}{logical}
#'   \item{GenMinFormerOwnersEndLE}{logical}
#'   \item{GenMinFormerOwnersEndList}{logical}
#'   \item{GenMaxFormerOwnersEndPI}{logical}
#'   \item{GenMaxFormerOwnersEndLE}{logical}
#'   \item{GenMaxFormerOwnersEndList}{logical}
#'   \item{GenAvgFormerOwnersEndPI}{logical}
#'   \item{GenAvgFormerOwnersEndLE}{logical}
#'   \item{GenAvgFormerOwnersEndList}{logical}
#'   \item{GenMinFormerOwnersAgePI}{logical}
#'   \item{GenMaxFormerOwnersAgePI}{logical}
#'   \item{GenAvgFormerOwnersAgePI}{logical}
#'   \item{GenCountFormerAdmin}{double}
#'   \item{GenMinFormerAdminEnd}{double}
#'   \item{GenMaxFormerAdminEnd}{double}
#'   \item{GenAvgFormerAdminEnd}{double}
#'   \item{GenCountFormerAdminPI}{double}
#'   \item{GenCountFormerAdminLE}{double}
#'   \item{GenCountFormerAdminList}{double}
#'   \item{GenMinFormerAdminEndPI}{double}
#'   \item{GenMinFormerAdminEndLE}{double}
#'   \item{GenMinFormerAdminEndList}{logical}
#'   \item{GenMaxFormerAdminEndPI}{double}
#'   \item{GenMaxFormerAdminEndLE}{double}
#'   \item{GenMaxFormerAdminEndList}{logical}
#'   \item{GenAvgFormerAdminEndPI}{double}
#'   \item{GenAvgFormerAdminEndLE}{double}
#'   \item{GenAvgFormerAdminEndList}{logical}
#'   \item{GenMinAFormerdminAgePI}{double}
#'   \item{GenMaxFormerAdminAgePI}{double}
#'   \item{GenAvgFormerAdminAgePI}{double}
#'   \item{GenCountFormerAuditor}{double}
#'   \item{GenMinFormerAuditorEnd}{double}
#'   \item{GenMaxFormerAuditorEnd}{double}
#'   \item{GenAvgFormerAuditorEnd}{double}
#'   \item{GenCountFormerAuditorPI}{double}
#'   \item{GenCountFormerAuditorLE}{double}
#'   \item{GenCountFormerAuditorList}{double}
#'   \item{GenMinFormerAuditorEndPI}{double}
#'   \item{GenMinFormerAuditorEndLE}{double}
#'   \item{GenMinFormerAuditorEndList}{logical}
#'   \item{GenMaxFormerAuditorEndPI}{double}
#'   \item{GenMaxFormerAuditorEndLE}{double}
#'   \item{GenMaxFormerAuditorEndList}{logical}
#'   \item{GenAvgFormerAuditorEndPI}{double}
#'   \item{GenAvgFormerAuditorEndLE}{double}
#'   \item{GenAvgFormerAuditorEndList}{logical}
#'   \item{OwnersPerChangeNew12M}{double}
#'   \item{OwnersPerChangeNew24M}{double}
#'   \item{OwnersPerChangeNew36M}{double}
#'   \item{OwnersNoChangeNew12M}{double}
#'   \item{OwnersNoChangeNew24M}{double}
#'   \item{OwnersNoChangeNew36M}{double}
#'   \item{AdminNoChangeNew12M}{double}
#'   \item{AdminNoChangeNew24M}{double}
#'   \item{AdminNoChangeNew36M}{double}
#'   \item{AuditorNoChangeNew12M}{double}
#'   \item{AuditorNoChangeNew24M}{double}
#'   \item{AuditorNoChangeNew36M}{double}
#'   \item{OwnersResPerChangeNew12M}{double}
#'   \item{OwnersResPerChangeNew24M}{double}
#'   \item{OwnersResPerChangeNew36M}{double}
#'   \item{OwnersResNoChangeNew12M}{double}
#'   \item{OwnersResNoChangeNew24M}{double}
#'   \item{OwnersResNoChangeNew36M}{double}
#'   \item{AdminResNoChangeNew12M}{double}
#'   \item{AdminResNoChangeNew24M}{double}
#'   \item{AdminResNoChangeNew36M}{double}
#'   \item{OwnersNonResPerChangeNew12M}{double}
#'   \item{OwnersNonResPerChangeNew24M}{double}
#'   \item{OwnersNonResPerChangeNew36M}{double}
#'   \item{OwnersNonResNoChangeNew12M}{double}
#'   \item{OwnersNonResNoChangeNew24M}{double}
#'   \item{OwnersNonResNoChangeNew36M}{double}
#'   \item{AdminNonResNoChangeNew12M}{double}
#'   \item{AdminNonResNoChangeNew24M}{double}
#'   \item{AdminNonResNoChangeNew36M}{double}
#' }
#'
#'
"CompanyData2018"
